submission_timestamp: '2026-05-21T15:30:54'
author_lastname: baseline
institute_abbreviation: BASEAL
sampling_strategy: random
dataset: BirdSet_BASEAL_latest/HSN_BASEAL
model: perch_v2
config:
  learning_rate: 0.001
  model_parameters: 2391572
  n_outer_repeats: 5
  pretrain_samples: 0
learning_curve:
- cycle: 1
  n_labeled: 50
  mAP_mean: 0.207001
  mAP_sd: 0.026806
  aulc_mAP_mean: 0.1035
  aulc_mAP_sd: 0.013403
  annotation_cost: 53
  sampling_time_s_mean: 0.000657
  sampling_time_s_sd: 3.1e-05
- cycle: 2
  n_labeled: 100
  mAP_mean: 0.292344
  mAP_sd: 0.037056
  aulc_mAP_mean: 0.176586
  aulc_mAP_sd: 0.022134
  annotation_cost: 51
  sampling_time_s_mean: 0.000695
  sampling_time_s_sd: 0.000198
- cycle: 3
  n_labeled: 150
  mAP_mean: 0.325285
  mAP_sd: 0.030995
  aulc_mAP_mean: 0.220662
  aulc_mAP_sd: 0.025695
  annotation_cost: 51
  sampling_time_s_mean: 0.000598
  sampling_time_s_sd: 2.0e-05
- cycle: 4
  n_labeled: 200
  mAP_mean: 0.350323
  mAP_sd: 0.024617
  aulc_mAP_mean: 0.249948
  aulc_mAP_sd: 0.02555
  annotation_cost: 52
  sampling_time_s_mean: 0.000584
  sampling_time_s_sd: 1.7e-05
- cycle: 5
  n_labeled: 250
  mAP_mean: 0.382737
  mAP_sd: 0.031479
  aulc_mAP_mean: 0.273264
  aulc_mAP_sd: 0.025518
  annotation_cost: 55
  sampling_time_s_mean: 0.000581
  sampling_time_s_sd: 1.7e-05
- cycle: 6
  n_labeled: 300
  mAP_mean: 0.406399
  mAP_sd: 0.035292
  aulc_mAP_mean: 0.293482
  aulc_mAP_sd: 0.025776
  annotation_cost: 55
  sampling_time_s_mean: 0.000709
  sampling_time_s_sd: 0.000182
- cycle: 7
  n_labeled: 350
  mAP_mean: 0.418092
  mAP_sd: 0.026199
  aulc_mAP_mean: 0.310448
  aulc_mAP_sd: 0.025396
  annotation_cost: 53
  sampling_time_s_mean: 0.000699
  sampling_time_s_sd: 0.000248
- cycle: 8
  n_labeled: 400
  mAP_mean: 0.418918
  mAP_sd: 0.030915
  aulc_mAP_mean: 0.323955
  aulc_mAP_sd: 0.025096
  annotation_cost: 55
  sampling_time_s_mean: 0.000696
  sampling_time_s_sd: 0.000217
- cycle: 9
  n_labeled: 450
  mAP_mean: 0.443097
  mAP_sd: 0.038345
  aulc_mAP_mean: 0.33585
  aulc_mAP_sd: 0.025843
  annotation_cost: 53
  sampling_time_s_mean: 0.000567
  sampling_time_s_sd: 9.0e-06
- cycle: 10
  n_labeled: 500
  mAP_mean: 0.444522
  mAP_sd: 0.03283
  aulc_mAP_mean: 0.346646
  aulc_mAP_sd: 0.026425
  annotation_cost: 54
  sampling_time_s_mean: 0.000591
  sampling_time_s_sd: 3.6e-05
supplementary:
  n_cycles: 10
  n_outer_repeats: 5
  total_annotation_cost_mean: 533.8
  total_annotation_cost_sd: 5.95
  total_sampling_time_s_mean: 0.006376
  total_sampling_time_s_sd: 0.000779
  computational_cost:
    model_parameters: 2391572
    epochs_per_cycle: 10
    n_cycles: 10
    cost_method: 239157200
    baseline_n_cycles: 10
    baseline_cost: 239157200
    relative_cost: 1.0
